### ISSUE TITLE
BrokenTest.plusTwo is returning "banana" should be 2

### ISSUE THREAD

**Issue by rninne** [rninne/x_appe_delivery#1]
https://github.com/rninne/x_appe_delivery/blob/e462652ef0d9e47a51b24684ad12e98b2a8c680b/9c76dafadb981d10f2f27d62f3961962/update/sys_script_include_e40936badb1c1d10f2f27d62f39619cc.xml#L20

**Comment by emprninness** [comment]
Fixed in #2

**Comment by rninne** [comment]
> Fixed in #2

You didn't fix the script, you just changed the test so that it would pass. . .

**Comment by ravikrt** [comment]
Yes, After changing 2 to "banana" in test step issue fixed.
